=== google/gnostic/cmd/protoc-gen-jsonschema/examples/tests/protobuftypes/schemas_json/Message.json
{
  "title": "Message",
  "$id": "http://example.com/schemas/Message.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "messageId": {
      "title": "messageId",
      "type": "string"
    },
    "stringType": {
      "title": "stringType",
      "type": "string"
    },
    "recursiveType": {
      "$ref": "http://example.com/schemas/RecursiveParent.json"
    },
    "embeddedType": {
      "$ref": "#/definitions/Message_EmbMessage"
    },
    "subType": {
      "$ref": "http://example.com/schemas/SubMessage.json"
    },
    "repeatedType": {
      "title": "repeatedType",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repeatedSubType": {
      "title": "repeatedSubType",
      "type": "array",
      "items": {
        "$ref": "http://example.com/schemas/SubMessage.json"
      }
    },
    "repeatedRecursiveType": {
      "title": "repeatedRecursiveType",
      "type": "array",
      "items": {
        "$ref": "http://example.com/schemas/RecursiveParent.json"
      }
    },
    "mapType": {
      "title": "mapType",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "body": {
      "title": "body",
      "type": "object"
    },
    "media": {
      "title": "media",
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "valueType": {
      "title": "valueType",
      "type": [
        "string",
        "number",
        "integer",
        "boolean",
        "object",
        "array"
      ],
      "description": "Description of value"
    },
    "repeatedValueType": {
      "title": "repeatedValueType",
      "type": "array",
      "items": {
        "type": [
          "string",
          "number",
          "integer",
          "boolean",
          "object",
          "array"
        ]
      },
      "description": "Description of repeated value"
    }
  },
  "definitions": {
    "Message_EmbMessage": {
      "title": "EmbMessage",
      "type": "object",
      "properties": {
        "messageId": {
          "title": "messageId",
          "type": "string"
        }
      }
    }
  }
}

=== google/gnostic/cmd/protoc-gen-jsonschema/examples/tests/protobuftypes/testdata_json/Message.json
{
  "messageId": "123abc",
  "stringType": "string",
  "recursiveType": {
    "parentId": 123,
    "child": {
      "childId": 456,
      "parent": {
        "parentId": 124,
        "child": {
          "childId": 457
        }
      }
    }
  },
  "embeddedType": {
    "messageId": "abc123"
  },
  "subType": {
    "messageId": "123abc",
    "subSubMessage": {
      "messageId": "abc123",
      "integers": [
        123,
        321
      ]
    }
  },
  "repeatedType": [
    "string1",
    "string2"
  ],
  "repeatedSubType": [
    {
      "messageId": "123abc",
      "subSubMessage": {
        "messageId": "abc123",
        "integers": [
          123,
          321
        ]
      }
    },
    {
      "messageId": "123abd",
      "subSubMessage": {
        "messageId": "abc124",
        "integers": [
          123,
          321
        ]
      }
    }
  ],
  "repeatedRecursiveType": [
    {
      "parentId": 123,
      "child": {
        "childId": 456,
        "parent": {
          "parentId": 124,
          "child": {
            "childId": 457
          }
        }
      }
    },
    {
      "parentId": 124,
      "child": {
        "childId": 457,
        "parent": {
          "parentId": 125,
          "child": {
            "childId": 458
          }
        }
      }
    }
  ],
  "mapType": {
    "key1": "val1",
    "key2": "val2"
  },
  "body": {
    "any": {
      "object": "here"
    }
  },
  "media": [
    {
      "any1": {
        "object1": "here"
      }
    },
    {
      "any2": {
        "object2": "here"
      }
    }
  ],
  "valueType": 123.321,
  "repeatedValueType": [
    123,
    321
  ]
}
