=== google/gnostic/cmd/protoc-gen-jsonschema/examples/tests/mapfields/schemas_json/Message.json
{
  "title": "Message",
  "$id": "http://example.com/schemas/Message.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "Message is the main way of communicating",
  "properties": {
    "messageId": {
      "title": "messageId",
      "type": "string",
      "description": "Message ID"
    },
    "anotherMessage": {
      "$ref": "http://example.com/schemas/AnotherMessage.json"
    },
    "subMessage": {
      "$ref": "#/definitions/SubMessage"
    },
    "stringList": {
      "title": "stringList",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "subMessageList": {
      "title": "subMessageList",
      "type": "array",
      "items": {
        "$ref": "#/definitions/SubMessage"
      }
    },
    "anotherMessageList": {
      "title": "anotherMessageList",
      "type": "array",
      "items": {
        "$ref": "http://example.com/schemas/AnotherMessage.json"
      }
    },
    "objectList": {
      "title": "objectList",
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "stringsMap": {
      "title": "stringsMap",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "subMessagesMap": {
      "title": "subMessagesMap",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/SubMessage"
      }
    },
    "anotherMessagesMap": {
      "title": "anotherMessagesMap",
      "type": "object",
      "additionalProperties": {
        "$ref": "http://example.com/schemas/AnotherMessage.json"
      }
    },
    "objectsMap": {
      "title": "objectsMap",
      "type": "object",
      "additionalProperties": {
        "type": "object"
      }
    }
  },
  "definitions": {
    "SubMessage": {
      "title": "SubMessage",
      "$id": "/schemas/SubMessage",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "id": {
          "title": "id",
          "type": "integer",
          "format": "int64"
        },
        "label": {
          "title": "label",
          "type": "string"
        }
      }
    }
  }
}

=== google/gnostic/cmd/protoc-gen-jsonschema/examples/tests/mapfields/testdata_json/Message.json
{
  "messageId": "123abc",
  "anotherMessage": {
    "id": 1234,
    "label": "The label"
  },
  "subMessage": {
    "id": 1234,
    "label": "The label"
  },
  "stringList": ["123", "abc"],
  "subMessageList": [
    {
      "id": 1234,
      "label": "The label"
    },
    {
      "id": 4321,
      "label": "Another label"
    }
  ],
  "anotherMessageList": [
    {
      "id": 1234,
      "label": "The label"
    },
    {
      "id": 4321,
      "label": "Another label"
    }
  ],
  "objectList": [
    {
      "any": "props",
      "should": "work"
    }
  ],
  "stringsMap": {
    "any": "props",
    "should": "work"
  },
  "subMessagesMap": {
    "sub1": {
      "id": 1234,
      "label": "The label"
    },
    "sub2": {
      "id": 4321,
      "label": "Another label"
    }
  },
  "anotherMessagesMap": {
    "another1": {
      "id": 1234,
      "label": "The label"
    },
    "another2": {
      "id": 4321,
      "label": "Another label"
    }
  },
  "objectsMap": {
    "object1": {
      "any": "props",
      "should": "work"
    },
    "object2": {
      "any": "props",
      "should": "work"
    }
  }
}
